In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [3]:
a=np.array(a)

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a=np.array(2)
a.ndim

0

In [7]:
a=np.array([2])
a.ndim

1

In [20]:
one=np.array(["preethi","raju","vanitha","vinay"])
one

array(['preethi', 'raju', 'vanitha', 'vinay'], dtype='<U7')

In [21]:
one.ndim

1

In [16]:
one=np.array([["preethi","raju","vanitha","vinay"],["preethi","raju","vanitha","vinay"]])
one

array([['preethi', 'raju', 'vanitha', 'vinay'],
       ['preethi', 'raju', 'vanitha', 'vinay']], dtype='<U7')

In [17]:
one.ndim

2

In [18]:
# If the values are not match 

# While inserting the values we have to mention the acces
# otherwise 2 dimention we convert to 1 dimention

# np.append(arr,values,axis=None)
import numpy as np
a=np.append(one,"maruthi")
a


array(['preethi', 'raju', 'vanitha', 'vinay', 'preethi', 'raju',
       'vanitha', 'vinay', 'maruthi'], dtype='<U7')

In [19]:
a=np.append(one,"maruthi",axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [14]:
a

array(['preethi', 'raju', 'vanitha', 'vinay', 'preethi', 'raju',
       'vanitha', 'vinay', 'maruthi'], dtype='<U7')

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshape=np.reshape(arr,(2,3))
print(reshape)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
reshape=np.reshape(arr,(2,2,2))
print(reshape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
a.shape

(3, 4)

In [14]:
print(a.min())

1


In [15]:
print(a.max())

12


In [17]:
for i in np.ndenumerate(a):
    print(i)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((1, 0), np.int64(5))
((1, 1), np.int64(6))
((1, 2), np.int64(7))
((1, 3), np.int64(8))
((2, 0), np.int64(9))
((2, 1), np.int64(10))
((2, 2), np.int64(11))
((2, 3), np.int64(12))


In [18]:
p1=([["a","b,","c"],["a","b","c"]])
p2=([["A","B","C"],["A","B","C"]])
np.hstack((p1,p2))

array([['a', 'b,', 'c', 'A', 'B', 'C'],
       ['a', 'b', 'c', 'A', 'B', 'C']], dtype='<U2')

In [19]:
np.vstack((p1,p2))

array([['a', 'b,', 'c'],
       ['a', 'b', 'c'],
       ['A', 'B', 'C'],
       ['A', 'B', 'C']], dtype='<U2')

In [20]:
# dstack
np.dstack((p1,p2))

array([[['a', 'A'],
        ['b,', 'B'],
        ['c', 'C']],

       [['a', 'A'],
        ['b', 'B'],
        ['c', 'C']]], dtype='<U2')